apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: poc-workflow-
spec:
  entrypoint: poc-workflow
  arguments:
    parameters:
    - name: dataset-source

  templates:
  - name: poc-workflow
    steps:
    - - name: poc-import
        template: poc-import
        arguments:
          parameters:
          - name: dataset-source
            value: "{{workflow.parameters.dataset-source}}"        
    - - name: poc-parser
        template: poc-parser
        arguments:
          artifacts:
          - name: dataset-csv
            from: "{{steps.poc-import.outputs.artifacts.dataset-csv}}"
    - - name: poc-persist
        template: poc-persist
        arguments:
          artifacts:
          - name: dataset-json
            from: "{{steps.poc-parser.outputs.artifacts.dataset-json}}"

  - name: poc-import
    inputs:
      parameters:
      - name: dataset-source
    container:
      image:  masalinasgancedo/poc-import
      command: [python3]
      args: ["import.py", "{{inputs.parameters.dataset-source}}"] 
    outputs:
      artifacts:
      - name: dataset-csv
        path: /app/covid-19.csv

  - name: poc-parser
    inputs:
      artifacts:
      - name: dataset-csv
        path: /app/covid-19.csv
    container:
      image:  masalinasgancedo/poc-parser
      command: [python3]
      args: ["parser.py", "covid-19.csv"]
    outputs:
      artifacts:
      - name: dataset-json
        path: /app/covid-19.json

  - name: poc-persist
    inputs:
      artifacts:
      - name: dataset-json
        path: /app/covid-19.json
    container:
      image:  masalinasgancedo/poc-persist
      command: [python3]
      args: ["persist.py", "covid-19.json"]        