apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: poc-workflow-
spec:
  entrypoint: poc-workflow
      
  templates:
  - name: poc-workflow
    steps:
    - - name: poc-import
        template: poc-import
    - - name: poc-parser
        template: poc-parser
        arguments:
          artifacts:
          - name: poc-data
            from: "{{steps.poc-import.outputs.artifacts.poc-data}}"

  - name: poc-import
    container:
      image:  masalinasgancedo/poc-import
      command: [python3]
      args: ["import.py"] 
    outputs:
      artifacts:
      - name: poc-data
        path: /app/gas.csv

  - name: poc-parser
    inputs:
      artifacts:
      - name: poc-data
        path: /app/gas.csv
    container:
      image:  masalinasgancedo/poc-parser
      command: [python3]
      args: ["parser.py", "gas.csv"]