apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: poc-artifact-workflow-
spec:
  entrypoint: poc-artifact-workflow
  podGC:
    # Pod GC strategy must be one of the following:
    # * OnPodCompletion - delete pods immediately when pod is completed (including errors/failures)
    # * OnPodSuccess - delete pods immediately when pod is successful
    # * OnWorkflowCompletion - delete pods when workflow is completed
    # * OnWorkflowSuccess - delete pods when workflow is successful
    strategy: OnWorkflowSuccess  
  arguments:
    parameters:
    - name: dataset-source

  templates:
  - name: poc-artifact-workflow
    steps:
    - - name: poc-artifact-import
        template: poc-artifact-import
        arguments:
          parameters:
          - name: dataset-source
            value: "{{workflow.parameters.dataset-source}}"        
    - - name: poc-artifact-parser
        template: poc-artifact-parser
        arguments:
          artifacts:
          - name: dataset-csv
            from: "{{steps.poc-artifact-import.outputs.artifacts.dataset-csv}}"
    - - name: poc-artifact-persist
        template: poc-artifact-persist
        arguments:
          artifacts:
          - name: dataset-json
            from: "{{steps.poc-artifact-parser.outputs.artifacts.dataset-json}}"

  - name: poc-artifact-import
    inputs:
      parameters:
      - name: dataset-source
    container:
      image:  masalinasgancedo/poc-artifact-import
      command: [python3]
      args: ["import.py", "{{inputs.parameters.dataset-source}}"] 
    outputs:
      artifacts:
      - name: dataset-csv
        path: /app/covid-19.csv

  - name: poc-artifact-parser
    inputs:
      artifacts:
      - name: dataset-csv
        path: /app/covid-19.csv
    container:
      image:  masalinasgancedo/poc-artifact-parser
      command: [python3]
      args: ["parser.py", "covid-19.csv"]
    outputs:
      artifacts:
      - name: dataset-json
        path: /app/covid-19.json

  - name: poc-artifact-persist
    inputs:
      artifacts:
      - name: dataset-json
        path: /app/covid-19.json
    container:
      image:  masalinasgancedo/poc-artifact-persist
      command: [python3]
      args: ["persist.py", "covid-19.json"]        